title: "Eason Tech Talk"
email: support@easontechtalk.com
timezone: UTC
baseurl: ""
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: Eason
paginate: 30
disqus: 'eason-tech-talk'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
  #https://github.com/untra/polyglot/issues/125
  sourcemap: never
ganalytics: G-3QPJPEHDZP

# Polyglot
languages: ["en", "tw"]
default_lang: "en"
exclude_from_localization: ["javascript", "images", "css", "public", "assets"]
parallel_localization: true

# Authors
authors:
  eason:
    name: Eason
    display_name: Eason Cao
    avatar: 'assets/images/authors/eason.jpg'
    email: support@easontechtalk.com
    web: https://easoncao.com
    twitter: https://twitter.com/EasonTechTalk
    description: "Eason is an engineer working at FANNG and living in Europe. He was accredited as AWS Professional Solution Architect, AWS Professional DevOps Engineer and CNCF Certified Kubernetes Administrator. He started his Kubernetes journey in 2017 and enjoys solving real-world business problems."

# Social
social:
  facebook: https://www.facebook.com/EasonTechTalk
  # instagram: https://www.instagram.com/bootstrapstarter/
  # twitter: https://twitter.com/EasonTechTalk

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
- jekyll-polyglot
